# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200701_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, null=True)),
                ('email', models.EmailField(default=0.0, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=30, null=True, verbose_name='书名'),
        ),
    ]
