# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-02 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20200701_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=7, verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=7, verbose_name='定价'),
        ),
    ]
