# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20200702_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=30, null=True, unique=True, verbose_name='书名'),
        ),
    ]
