# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-06 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20200702_0857'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='myauthor',
        ),
    ]
