# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-07 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20200707_1900'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='bookstore_author',
        ),
    ]
