# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-07 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20200707_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wife',
            name='author',
        ),
        migrations.DeleteModel(
            name='Wife',
        ),
    ]
